server:
  tomcat:
    max-threads: 4
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo

logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    org.springframework.cloud: INFO
    org.springframework.web: INFO