server:
  tomcat:
    max-threads: 4
  port: 0
  forward-headers-strategy: native

eureka:
   client:
      healthcheck:
        enabled: true
      service-url:
         defaultZone: http://localhost:8562/eureka
   instance:
      preferIpAddress: true
      instance-id: ${spring.application.name}-${random.uuid}

logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
  http:
    encoding:
      enabled: true
      force: true
      charset: ISO-8859-1
  messages:
    basename: messages
    encoding: ISO-8859-1
    
security:
  oauth2:
    client:
      client-id: clientId
      client-secret: user
    resource:
      token-info-uri: http://localhost:8082/authentication/oauth/check_token

    