server:
  tomcat:
    max-threads: 4
  port: 8082
  forward-headers-strategy: native
  servlet:
    context-path: /${spring.application.name}
    
eureka:
   client:
      enabled: false

logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    org.springframework.web: INFO
    
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    jdbc-url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: user      
    resource:
      token-info-uri: http://localhost:8082/authentication/oauth/check_token
      id: product_api
      


