server:
  tomcat:
    max-threads: 4
  port: 8082
  forward-headers-strategy: native
  servlet:
    context-path: /${spring.application.name}
    
eureka:
   client:
      enabled: false

logging:
  file:
    name: logs/${spring.application.name}/${spring.application.name}.log
    max-size: 10MB
    max-history: 50
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
        
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
  http:
    encoding:
      enabled: true # Enable http encoding support.
      force: true # Force the encoding to the configured charset on HTTP requests and responses.
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type".
  messages:
    basename: messages
    encoding: ISO-8859-1

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: user
    resource:
      token-info-uri: http://localhost:8082/authentication/oauth/check_token

