server:
  tomcat:
    max-threads: 4
  port: 0
  forward-headers-strategy: native

eureka:
   client:
      healthcheck:
        enabled: true
      service-url:
         defaultZone: http://localhost:8562/eureka
   instance:
      preferIpAddress: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    jdbc-url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

    