spring:
  profiles:
    active: dev
  
  main:
    allow-bean-definition-overriding: true
    
management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
      restart:
         enabled: true
      shutdown:
         enabled: true