server:
  tomcat:
    max-threads: 4
  port: 8082
  forward-headers-strategy: native
  servlet:
    context-path: /${spring.application.name}

eureka:
   client:
      enabled: false
      
logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: user
    resource:
      token-info-uri: http://localhost:8082/authentication/oauth/check_token
      id: product_api
      
      