spring:
  profiles:
    active: dev
    
management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
      restart:
         enabled: true
      shutdown:
         enabled: true