server:
  tomcat:
    max-threads: 4
  port: 8563

spring:
  boot:
    admin:
      discovery:
        ignored-services: gateway

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instanceId : ${spring.application.name}-${random.uuid}
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8562/eureka
      
logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    org.springframework.cloud: INFO
    org.springframework.web: INFO

