server:
  tomcat:
    max-threads: 4
  port: 0
  forward-headers-strategy: native

eureka:
   client:
      healthcheck:
        enabled: true
      service-url:
         defaultZone: http://localhost:8562/eureka
   instance:
      preferIpAddress: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
            
logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO

