spring:
  profiles:
    active: dev
management:
  endpoints:      
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true