server:
  tomcat:
    max-threads: 4
  port: 8562

eureka:  
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8562/eureka
      
logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  level:
    org:
      springframework:
        cloud: INFO
        web: INFO

